import React, { useState, useMemo } from 'react';
import { PipelineNode, Connection } from './types';

interface PreviewProps {
  nodes: PipelineNode[];
  connections: Connection[];
}

type PreviewTab = 'code' | 'graph';

export const Preview: React.FC<PreviewProps> = ({ nodes, connections }) => {
  const [activeTab, setActiveTab] = useState<PreviewTab>('code');

  // Generate code from pipeline
  const generatedCode = useMemo(() => {
    if (nodes.length === 0) {
      return `# No nodes added yet
# Drag nodes from the left panel to start building

from nl_builder import Pipeline, Agent, Node

# Example:
# pipeline = Pipeline()
# pipeline.add_node(Agent("ChatAgent"))
# await pipeline.run()
`;

    }

    let code = `"""
Auto-generated Pipeline Code
Generated by NL Builder
"""

from nl_builder import Pipeline, Agent, Node, Connection

# Initialize Pipeline
pipeline = Pipeline(
    name="Generated Pipeline",
    description="Auto-generated from visual builder"
)

`;

    // Add nodes
    const nodeMap: Record<string, string> = {};
    nodes.forEach((node, index) => {
      const varName = `${node.data.type}_${index}`;
      nodeMap[node.id] = varName;

      const configStr = node.data.config
        ? `,\n    config=${JSON.stringify(node.data.config, null, 6)}`
        : '';

      code += `# ${node.data.label}
${varName} = ${node.data.type.capitalize()}(
    id="${node.id}",
    name="${node.data.label}"${configStr}
)
pipeline.add_node(${varName})

`;
    });

    // Add connections
    if (connections.length > 0) {
      code += `\n# Connections\n`;
      connections.forEach((conn) => {
        const sourceVar = nodeMap[conn.sourceId];
        const targetVar = nodeMap[conn.targetId];
        if (sourceVar && targetVar) {
          code += `pipeline.connect(${sourceVar}, ${targetVar})\n`;
        }
      });
    }

    // Add execution code
    code += `

# Run pipeline
if __name__ == "__main__":
    import asyncio
    
    async def main():
        result = await pipeline.run()
        return result
    
    asyncio.run(main())
`;

    return code;
  }, [nodes, connections]);

  // Generate graph representation (Mermaid style)
  const graphPreview = useMemo(() => {
    if (nodes.length === 0) {
      return `graph TD
    A[No nodes] --> B[Add nodes to start]`;
    }

    let graph = `graph TD\n`;
    
    // Define nodes
    nodes.forEach((node) => {
      const label = node.data.label.replace(/"/g, '\\"');
      const nodeType = node.data.type;
      const color = {
        agent: '#3b82f6',
        pipeline: '#10b981',
        custom: '#f59e0b',
      }[nodeType] || '#6b7280';

      graph += `    ${node.id}["${label}"]:::${nodeType}\n`;
    });

    // Define styles
    graph += `\n    classDef agent fill:#3b82f6,stroke:#2563eb,color:#fff\n`;
    graph += `    classDef pipeline fill:#10b981,stroke:#059669,color:#fff\n`;
    graph += `    classDef custom fill:#f59e0b,stroke:#d97706,color:#fff\n`;

    // Define connections
    graph += `\n    %% Connections\n`;
    connections.forEach((conn) => {
      graph += `    ${conn.sourceId} --> ${conn.targetId}\n`;
    });

    return graph;
  }, [nodes, connections]);

  const handleDeploy = async () => {
    // Placeholder for deployment logic
    console.log('Deploying pipeline...', { nodes, connections });
    
    // Simulate deployment
    alert('Pipeline deployment initiated!\n\nIn production, this would:\n1. Validate the pipeline\n2. Deploy to cloud\n3. Return deployment URL');
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(generatedCode);
    alert('Code copied to clipboard!');
  };

  return (
    <div className="preview-panel">
      <div className="preview-header">
        <h3>Preview</h3>
        <button
          className="btn btn-success"
          onClick={handleDeploy}
          disabled={nodes.length === 0}
        >
          🚀 Deploy
        </button>
      </div>

      <div className="preview-tabs">
        <button
          className={`preview-tab ${activeTab === 'code' ? 'active' : ''}`}
          onClick={() => setActiveTab('code')}
        >
          Code
        </button>
        <button
          className={`preview-tab ${activeTab === 'graph' ? 'active' : ''}`}
          onClick={() => setActiveTab('graph')}
        >
          Graph
        </button>
      </div>

      <div className="preview-content">
        {activeTab === 'code' ? (
          <pre className="preview-code">{generatedCode}</pre>
        ) : (
          <pre className="preview-code" style={{ background: '#f8f9fa', color: '#333' }}>
            {graphPreview}
          </pre>
        )}
      </div>

      <div className="preview-actions">
        <button className="btn btn-secondary" onClick={handleCopy}>
          📋 Copy
        </button>
        <button
          className="btn btn-primary"
          onClick={() => {
            const blob = new Blob([generatedCode], { type: 'text/plain' });
            const url = URL.createObjectURL(blob);
            const a = document.createElement('a');
            a.href = url;
            a.download = 'pipeline.py';
            a.click();
            URL.revokeObjectURL(url);
          }}
          disabled={nodes.length === 0}
        >
          💾 Export
        </button>
      </div>
    </div>
  );
};

export default Preview;
