import React, { useState } from 'react';
import { PipelineState, Viewport } from './types';

interface ToolbarProps {
  pipelineState: PipelineState;
  onSave: (state: PipelineState) => void;
  onLoad: (state: PipelineState) => void;
  onExport: (state: PipelineState) => void;
  onImport: (file: File) => void;
  onUndo: () => void;
  onRedo: () => void;
  onDeleteSelected: () => void;
  onZoomIn: () => void;
  onZoomOut: () => void;
  onZoomReset: () => void;
  canUndo: boolean;
  canRedo: boolean;
}

export const Toolbar: React.FC<ToolbarProps> = ({
  pipelineState,
  onSave,
  onLoad,
  onExport,
  onImport,
  onUndo,
  onRedo,
  onDeleteSelected,
  onZoomIn,
  onZoomOut,
  onZoomReset,
  canUndo,
  canRedo,
}) => {
  const [showDropdown, setShowDropdown] = useState<string | null>(null);
  const [fileName, setFileName] = useState('untitled-pipeline');

  const handleSave = () => {
    onSave(pipelineState);
    const json = JSON.stringify(pipelineState, null, 2);
    const blob = new Blob([json], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${fileName}.json`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleLoad = (event: React.ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0];
    if (file) {
      setFileName(file.name.replace('.json', ''));
      onImport(file);
    }
  };

  const handleExport = () => {
    const code = generatePipelineCode(pipelineState);
    const blob = new Blob([code], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${fileName}.py`;
    a.click();
    URL.revokeObjectURL(url);
    onExport(pipelineState);
  };

  const generatePipelineCode = (state: PipelineState): string => {
    if (state.nodes.length === 0) {
      return '# Empty pipeline';
    }

    let code = `"""
Auto-generated Pipeline Code
Generated by NL Builder
"""

from nl_builder import Pipeline, Agent, Node, Connection

# Initialize Pipeline
pipeline = Pipeline(
    name="${fileName}",
    description="Auto-generated from visual builder"
)

`;

    const nodeMap: Record<string, string> = {};
    state.nodes.forEach((node, index) => {
      const varName = `${node.data.type}_${index}`;
      nodeMap[node.id] = varName;

      const configStr = node.data.config
        ? `,\n    config=${JSON.stringify(node.data.config, null, 6)}`
        : '';

      code += `# ${node.data.label}
${varName} = ${node.data.type.charAt(0).toUpperCase() + node.data.type.slice(1)}(
    id="${node.id}",
    name="${node.data.label}"${configStr}
)
pipeline.add_node(${varName})

`;
    });

    if (state.connections.length > 0) {
      code += `\n# Connections\n`;
      state.connections.forEach((conn) => {
        const sourceVar = nodeMap[conn.sourceId];
        const targetVar = nodeMap[conn.targetId];
        if (sourceVar && targetVar) {
          code += `pipeline.connect(${sourceVar}, ${targetVar})\n`;
        }
      });
    }

    code += `

if __name__ == "__main__":
    import asyncio
    
    async def main():
        result = await pipeline.run()
        return result
    
    asyncio.run(main())
`;

    return code;
  };

  return (
    <div className="toolbar">
      {/* File operations */}
      <div style={{ position: 'relative' }}>
        <button
          className="toolbar-btn"
          onClick={() => setShowDropdown(showDropdown === 'file' ? null : 'file')}
        >
          📁 File
        </button>
        {showDropdown === 'file' && (
          <div
            style={{
              position: 'absolute',
              top: '100%',
              left: 0,
              marginTop: '4px',
              background: '#fff',
              border: '1px solid #e0e0e0',
              borderRadius: '8px',
              boxShadow: '0 4px 12px rgba(0,0,0,0.1)',
              minWidth: '180px',
              zIndex: 100,
            }}
          >
            <button
              className="toolbar-btn"
              style={{ width: '100%', borderRadius: 0, justifyContent: 'flex-start' }}
              onClick={handleSave}
            >
              💾 Save
            </button>
            <button
              className="toolbar-btn"
              style={{ width: '100%', borderRadius: 0, justifyContent: 'flex-start' }}
              onClick={() => document.getElementById('load-input')?.click()}
            >
              📂 Load
            </button>
            <input
              id="load-input"
              type="file"
              accept=".json"
              style={{ display: 'none' }}
              onChange={handleLoad}
            />
            <button
              className="toolbar-btn"
              style={{ width: '100%', borderRadius: 0, justifyContent: 'flex-start' }}
              onClick={handleExport}
            >
              📤 Export
            </button>
          </div>
        )}
      </div>

      <div className="toolbar-divider" />

      {/* Edit operations */}
      <button
        className="toolbar-btn"
        onClick={onUndo}
        disabled={!canUndo}
        title="Undo"
      >
        ↩️
      </button>
      <button
        className="toolbar-btn"
        onClick={onRedo}
        disabled={!canRedo}
        title="Redo"
      >
        ↪️
      </button>
      <button
        className="toolbar-btn danger"
        onClick={onDeleteSelected}
        disabled={!pipelineState.selectedNodeId && !pipelineState.selectedConnectionId}
        title="Delete Selected"
      >
        🗑️
      </button>

      <div className="toolbar-divider" />

      {/* Zoom controls */}
      <button className="toolbar-btn" onClick={onZoomOut} title="Zoom Out">
        🔍-
      </button>
      <button
        className="toolbar-btn"
        onClick={onZoomReset}
        title="Reset Zoom"
        style={{ minWidth: '50px' }}
      >
        {Math.round(pipelineState.viewport.zoom * 100)}%
      </button>
      <button className="toolbar-btn" onClick={onZoomIn} title="Zoom In">
        🔍+
      </button>

      {/* Pipeline info */}
      <div className="toolbar-divider" />
      <div
        style={{
          fontSize: '12px',
          color: '#666',
          padding: '0 8px',
        }}
      >
        {pipelineState.nodes.length} nodes • {pipelineState.connections.length} connections
      </div>

      {/* Click outside to close dropdown */}
      {showDropdown && (
        <div
          style={{
            position: 'fixed',
            top: 0,
            left: 0,
            right: 0,
            bottom: 0,
            zIndex: 50,
          }}
          onClick={() => setShowDropdown(null)}
        />
      )}
    </div>
  );
};

export default Toolbar;
